In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Activation, Dense, Dropout
from keras import optimizers
from sklearn.metrics import confusion_matrix,accuracy_score, roc_curve, auc
%matplotlib inline

In [83]:
import warnings
warnings.filterwarnings('ignore')

In [84]:
df1 = pd.read_csv("random_imputed.csv",index_col=[0])
df1.sample(5)

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
inpatient.number,,,,,,,,,,,,,,,,,,,,,
768711,0,36.0,72,19,102,70,80.666667,16.649324,0,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,100
775387,0,36.4,86,18,118,76,90.000000,22.892820,0,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,65
815803,0,36.3,119,20,110,70,83.333333,20.811655,0,3,...,22.800000,0.400000,89.000000,58.000000,68.610000,16.60000,1.100000,144.000000,15,65
786820,1,36.2,96,19,152,60,90.666667,17.898023,2,3,...,15.600000,0.300000,98.000000,138.000000,97.500000,10.50000,1.100000,103.000000,15,85
744206,0,36.3,131,19,134,96,108.666667,20.519134,2,2,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,85

In [85]:
df3=pd.read_csv("drug_onehot_latest.csv",index_col=[0])
df3.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
inpatient.number,,,,,,,,,,,,,,,,,,
722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [86]:
df1.drop(['hydroxybutyrate.dehydrogenase.to.lactate.dehydrogenase','hydroxybutyrate.dehydrogenase','free.calcium','anion.gap','lactate.dehydrogenase','lactate','CCI.score','consciousness','eye.opening','verbal.response','respiratory.support.','gender','ageCat'],axis=1,inplace=True)

In [87]:
q='Atorvastatin calcium tablet'

In [88]:
df2=df3[q]

In [89]:
df=pd.concat([df1,df3[q]],axis=1)

In [90]:
df.head()

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS,Atorvastatin calcium tablet
inpatient.number,,,,,,,,,,,,,,,,,,,,,
722128,36.9,66,18,121,56,77.666667,18.590125,2,4,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
723327,36.0,72,25,150,80,103.333333,21.644121,2,4,1,...,3.700000,-3.50000,21.900000,0.700000,91.000000,64.000000,90.000000,73.000000,15,1
723617,36.4,70,20,120,80,93.333333,33.157648,2,3,2,...,5.300000,3.90000,27.500000,0.000000,98.000000,106.000000,97.700000,104.000000,15,1
724385,36.7,129,25,122,86,98.000000,20.134780,2,3,3,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
725509,36.9,100,20,95,65,75.000000,22.031726,2,3,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0

In [91]:
cols_to_scale = [df.columns]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)

In [92]:
df = pd.DataFrame(scaled_df,columns = df.columns)

In [93]:
df.head()

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS,Atorvastatin calcium tablet
0,0.409463,0.293103,0.125,0.480159,0.383562,0.226534,0.275119,1.0,1.0,0.000000,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
1,0.000000,0.344828,1.000,0.595238,0.547945,0.555651,0.427086,1.0,1.0,0.000000,...,0.087536,0.496900,0.453679,0.268199,0.702676,0.227979,0.701541,0.101498,1.0,1.0
2,0.181984,0.327586,0.375,0.476190,0.547945,0.427423,1.000000,1.0,0.5,0.333333,...,0.165346,0.776631,0.670658,0.000000,0.933928,0.445596,0.954083,0.359401,1.0,1.0
3,0.318471,0.836207,1.000,0.484127,0.589041,0.487263,0.351981,1.0,0.5,0.666667,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
4,0.409463,0.586207,0.375,0.376984,0.445205,0.192341,0.446373,1.0,0.5,0.000000,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0

In [94]:
X = df.drop(q,axis='columns')
y = testLabels = df[q].astype(np.float32)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [95]:
y_train.value_counts()

0.0    948
1.0    654
Name: Atorvastatin calcium tablet, dtype: int64

In [96]:
y.value_counts()

0.0    1185
1.0     818
Name: Atorvastatin calcium tablet, dtype: int64

In [97]:
X = df.drop(q,axis='columns')
y = df[q]

In [98]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df = pd.concat([PCA_df, df[q]], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,Atorvastatin calcium tablet
0,-0.572855,0.775703,-0.555175,-0.668609,0.206971,0.311069,0.004777,-0.218921,0.021354,0.522483,...,0.117052,0.313998,0.083378,0.270367,0.613181,-0.032338,-0.291381,-0.346303,-0.057003,0.0
1,0.378881,-0.054257,-0.140639,-0.745776,0.054000,-0.078432,0.065719,-0.312667,-0.300151,0.531537,...,0.130041,-0.281455,-0.216349,0.080771,0.129352,0.079545,-0.117099,0.032437,0.089642,1.0
2,0.378855,-0.298639,-0.214987,-0.136841,-0.174487,0.944021,0.676052,0.005444,0.292429,-0.035979,...,0.162750,0.056158,0.233953,0.037804,-0.182907,0.073337,0.190404,0.210340,-0.395110,1.0
3,-0.385298,0.650624,-0.147322,-0.262479,0.156089,0.317733,-0.001556,-0.057074,0.389654,0.725043,...,-0.025797,0.037880,0.050543,0.093189,0.009083,0.240156,-0.030918,0.150497,-0.147013,0.0
4,-0.721262,-0.141627,0.296722,0.191071,-0.157643,-0.106280,0.209430,0.399258,-0.148421,0.039294,...,-0.083293,0.046128,-0.067033,0.065144,0.102891,0.149844,0.059303,-0.015103,-0.049884,0.0

In [99]:
count_class_0, count_class_1 = PCA_df[q].value_counts()

# Divide by class
df_class_0 = PCA_df[PCA_df[q] == 0]
df_class_1 = PCA_df[PCA_df[q] == 1]

In [100]:
PCA_df[q].value_counts()

0.0    1185
1.0     818
Name: Atorvastatin calcium tablet, dtype: int64

In [101]:
# Oversample 1-class and concat the DataFrames of both classes
df_class_1_over = df_class_1.sample(count_class_0, replace=True)
df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

print('Random over-sampling:')
print(df_test_over[q].value_counts())

Random over-sampling:
0.0    1185
1.0    1185
Name: Atorvastatin calcium tablet, dtype: int64

In [102]:
X = df_test_over.drop(q,axis='columns')
y = df_test_over[q]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [103]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)

In [104]:
predictions = mlp.predict(X_test)

In [105]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[183  54]
 [ 41 196]]
              precision    recall  f1-score   support

         0.0       0.82      0.77      0.79       237
         1.0       0.78      0.83      0.80       237

    accuracy                           0.80       474
   macro avg       0.80      0.80      0.80       474
weighted avg       0.80      0.80      0.80       474

In [106]:
mlp1 = MLPClassifier(solver='adam', activation='relu',alpha=1e-4,hidden_layer_sizes=(50,50,50), random_state=1,max_iter=50,verbose=10,learning_rate_init=.1)
history=mlp1.fit(X_train, y_train.values.ravel())

Iteration 1, loss = 0.97488791
Iteration 2, loss = 0.66533249
Iteration 3, loss = 0.61210424
Iteration 4, loss = 0.52898232
Iteration 5, loss = 0.44964139
Iteration 6, loss = 0.39511398
Iteration 7, loss = 0.38771927
Iteration 8, loss = 0.35454859
Iteration 9, loss = 0.29790897
Iteration 10, loss = 0.23684528
Iteration 11, loss = 0.25727541
Iteration 12, loss = 0.25057944
Iteration 13, loss = 0.21228182
Iteration 14, loss = 0.22199100
Iteration 15, loss = 0.25250307
Iteration 16, loss = 0.23985897
Iteration 17, loss = 0.19739702
Iteration 18, loss = 0.14196751
Iteration 19, loss = 0.15659792
Iteration 20, loss = 0.18358376
Iteration 21, loss = 0.22064935
Iteration 22, loss = 0.18842148
Iteration 23, loss = 0.17824966
Iteration 24, loss = 0.14785080
Iteration 25, loss = 0.13424393
Iteration 26, loss = 0.13306074
Iteration 27, loss = 0.17556763
Iteration 28, loss = 0.16542306
Iteration 29, loss = 0.15317991
Iteration 30, loss = 0.11987519
Iteration 31, loss = 0.16363358
Iteration 32, loss = 0.23582147
Iteration 33, loss = 0.19560545
Iteration 34, loss = 0.13645596
Iteration 35, loss = 0.10861612
Iteration 36, loss = 0.09686810
Iteration 37, loss = 0.10210295
Iteration 38, loss = 0.11344509
Iteration 39, loss = 0.11540027
Iteration 40, loss = 0.10076620
Iteration 41, loss = 0.10765318
Iteration 42, loss = 0.11648501
Iteration 43, loss = 0.10774865
Iteration 44, loss = 0.09862874
Iteration 45, loss = 0.08956104
Iteration 46, loss = 0.08266284
Iteration 47, loss = 0.13010454
Iteration 48, loss = 0.11493040
Iteration 49, loss = 0.12329660
Iteration 50, loss = 0.11605178

In [107]:
predictions1 = mlp1.predict(X_test)

In [108]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[183  54]
 [ 41 196]]
              precision    recall  f1-score   support

         0.0       0.82      0.77      0.79       237
         1.0       0.78      0.83      0.80       237

    accuracy                           0.80       474
   macro avg       0.80      0.80      0.80       474
weighted avg       0.80      0.80      0.80       474