In [21]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
df1 = pd.read_csv("random_imputed.csv",index_col=[0])
df1.sample(5)

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
inpatient.number,,,,,,,,,,,,,,,,,,,,,
849274,0,36.2,75,20,112,85,94.000000,18.359375,2,2,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,65
761974,1,36.2,52,19,152,86,108.000000,22.773186,2,3,...,24.500000,0.300000,95.000000,83.000000,94.900000,13.40000,1.150000,127.000000,15,65
802296,1,36.3,71,20,190,110,136.666667,23.661439,2,2,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,85
775491,0,36.2,65,17,116,60,78.666667,14.172336,2,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,85
770977,1,36.2,80,18,160,100,120.000000,17.578125,0,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,85

In [24]:
df3=pd.read_csv("drug_onehot_latest.csv",index_col=[0])
df3.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
inpatient.number,,,,,,,,,,,,,,,,,,
722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [25]:
df2=df3['Atorvastatin calcium tablet']

In [26]:
df=pd.concat([df1,df3['Atorvastatin calcium tablet']],axis=1)

In [27]:
df.head()

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat,Atorvastatin calcium tablet
inpatient.number,,,,,,,,,,,,,,,,,,,,,
722128,0,36.9,66,18,121,56,77.666667,18.590125,2,4,...,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,75,0
723327,0,36.0,72,25,150,80,103.333333,21.644121,2,4,...,0.700000,91.000000,64.000000,90.000000,13.00000,1.110000,73.000000,15,65,1
723617,1,36.4,70,20,120,80,93.333333,33.157648,2,3,...,0.000000,98.000000,106.000000,97.700000,9.10000,1.110000,104.000000,15,85,1
724385,1,36.7,129,25,122,86,98.000000,20.134780,2,3,...,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,75,0
725509,0,36.9,100,20,95,65,75.000000,22.031726,2,3,...,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,45,0

In [20]:
cols_to_scale = [df.columns]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)

In [9]:
df = pd.DataFrame(scaled_df,columns = df.columns)

In [10]:
df.head()

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat,Atorvastatin calcium tablet
0,0.0,0.271429,0.333333,0.500000,0.480159,0.383562,0.428309,0.046006,1.0,1.0,...,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.666667,0.0
1,0.0,0.142857,0.363636,0.583333,0.595238,0.547945,0.569853,0.053564,1.0,1.0,...,0.132075,0.880000,0.187234,0.878342,0.316258,0.440000,0.226190,1.0,0.533333,1.0
2,1.0,0.200000,0.353535,0.555556,0.476190,0.547945,0.514706,0.076992,1.0,0.5,...,0.000000,0.973333,0.365957,0.981283,0.229399,0.440000,0.410714,1.0,0.800000,1.0
3,1.0,0.242857,0.651515,0.611111,0.484127,0.589041,0.540441,0.049828,1.0,0.5,...,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.666667,0.0
4,0.0,0.271429,0.505051,0.555556,0.376984,0.445205,0.413603,0.054523,1.0,0.5,...,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.266667,0.0

In [11]:
X = df.drop('Atorvastatin calcium tablet',axis='columns')
y = testLabels = df['Atorvastatin calcium tablet'].astype(np.float32)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [12]:
y_train.value_counts()

0.0    948
1.0    654
Name: Atorvastatin calcium tablet, dtype: int64

In [13]:
y.value_counts()

0.0    1185
1.0     818
Name: Atorvastatin calcium tablet, dtype: int64

In [14]:
X = df.drop('Atorvastatin calcium tablet',axis='columns')
y = df['Atorvastatin calcium tablet']

In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df = pd.concat([PCA_df, df['Atorvastatin calcium tablet']], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,Atorvastatin calcium tablet
0,-0.523476,-0.238780,0.704734,-0.251208,-0.704963,0.083239,-0.016321,-0.338960,-0.101965,-0.320476,...,0.138977,-0.090525,0.044719,-0.039023,-0.074408,0.051322,0.048233,-0.095420,-0.117281,0.0
1,0.170270,-0.465586,-0.305915,-0.404152,-0.197291,0.284409,-0.234281,-0.308266,0.124785,-0.735082,...,0.086144,0.077468,-0.026543,-0.035970,-0.196330,-0.088867,-0.180740,-0.027363,0.073743,1.0
2,0.654504,0.359562,-0.358608,-0.289298,-0.006726,-0.024271,-0.087419,0.293584,-0.030858,-0.270481,...,-0.082718,0.154134,-0.006525,-0.048231,-0.018546,0.037308,0.100942,-0.006716,0.212511,1.0
3,-0.045029,0.771255,0.576467,-0.112582,-0.453351,-0.281525,0.753308,-0.256638,-0.458042,0.048076,...,-0.047436,-0.093628,-0.014237,0.117447,0.159251,-0.136388,-0.017576,0.007260,0.066017,0.0
4,-0.753907,-0.061010,-0.256266,-0.156085,0.005529,0.046611,-0.245375,-0.039222,-0.447446,0.192799,...,0.002370,0.107162,0.069440,0.113330,0.017976,-0.023594,-0.014171,-0.010660,0.057907,0.0

In [16]:
count_class_0, count_class_1 = PCA_df['Atorvastatin calcium tablet'].value_counts()

# Divide by class
df_class_0 = PCA_df[PCA_df['Atorvastatin calcium tablet'] == 0]
df_class_1 = PCA_df[PCA_df['Atorvastatin calcium tablet'] == 1]

In [17]:
PCA_df['Atorvastatin calcium tablet'].value_counts()

0.0    1185
1.0     818
Name: Atorvastatin calcium tablet, dtype: int64

In [18]:
# Oversample 1-class and concat the DataFrames of both classes
df_class_1_over = df_class_1.sample(count_class_0, replace=True)
df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

print('Random over-sampling:')
print(df_test_over['Atorvastatin calcium tablet'].value_counts())

Random over-sampling:
0.0    1185
1.0    1185
Name: Atorvastatin calcium tablet, dtype: int64

In [19]:
X = df_test_over.drop('Atorvastatin calcium tablet',axis='columns')
y = df_test_over['Atorvastatin calcium tablet']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [75]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(64, 32, 16), max_iter=1000)

In [76]:
predictions = mlp.predict(X_test)

In [77]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[176  61]
 [ 48 189]]
              precision    recall  f1-score   support

         0.0       0.79      0.74      0.76       237
         1.0       0.76      0.80      0.78       237

    accuracy                           0.77       474
   macro avg       0.77      0.77      0.77       474
weighted avg       0.77      0.77      0.77       474

In [93]:
mlp1 = MLPClassifier(solver='adam', activation='relu',alpha=1e-4,hidden_layer_sizes=(50,50,50), random_state=1,max_iter=50,verbose=10,learning_rate_init=.1)
mlp1.fit(X_train, y_train.values.ravel())

Iteration 1, loss = 0.95396928
Iteration 2, loss = 0.64596056
Iteration 3, loss = 0.59157599
Iteration 4, loss = 0.53553773
Iteration 5, loss = 0.46997606
Iteration 6, loss = 0.43303637
Iteration 7, loss = 0.38033503
Iteration 8, loss = 0.36657987
Iteration 9, loss = 0.35465381
Iteration 10, loss = 0.31975104
Iteration 11, loss = 0.26504546
Iteration 12, loss = 0.25150257
Iteration 13, loss = 0.23733031
Iteration 14, loss = 0.24809523
Iteration 15, loss = 0.22833423
Iteration 16, loss = 0.18371829
Iteration 17, loss = 0.18183230
Iteration 18, loss = 0.16279616
Iteration 19, loss = 0.16198023
Iteration 20, loss = 0.14535771
Iteration 21, loss = 0.13148539
Iteration 22, loss = 0.11326029
Iteration 23, loss = 0.09958233
Iteration 24, loss = 0.12680980
Iteration 25, loss = 0.18305061
Iteration 26, loss = 0.13685199
Iteration 27, loss = 0.10755481
Iteration 28, loss = 0.10410700
Iteration 29, loss = 0.12701035
Iteration 30, loss = 0.13287031
Iteration 31, loss = 0.15332008
Iteration 32, loss = 0.12484540
Iteration 33, loss = 0.08591548
Iteration 34, loss = 0.09296843
Iteration 35, loss = 0.10377707
Iteration 36, loss = 0.07746441
Iteration 37, loss = 0.07627037
Iteration 38, loss = 0.06824599
Iteration 39, loss = 0.08201524
Iteration 40, loss = 0.06112241
Iteration 41, loss = 0.04429891
Iteration 42, loss = 0.04479478
Iteration 43, loss = 0.04146299
Iteration 44, loss = 0.10400793
Iteration 45, loss = 0.10313478
Iteration 46, loss = 0.06290393
Iteration 47, loss = 0.10205563
Iteration 48, loss = 0.09566512
Iteration 49, loss = 0.12288948
Iteration 50, loss = 0.09323444

MLPClassifier(hidden_layer_sizes=(50, 50, 50), learning_rate_init=0.1,
              max_iter=50, random_state=1, verbose=10)

In [94]:
predictions1 = mlp1.predict(X_test)

In [1]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

NameError: name 'y_test' is not defined