# Importing Libraries

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix , classification_report

In [3]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
df1 = pd.read_csv(r"C:\Users\vinayak\minor_proj\collabRV\collabRV\Z_Current\Sets\random_imputed_2.csv",index_col=[0])
df1.sample(5)

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,reduced.hemoglobin,potassium.ion,chloride.ion,sodium.ion,glucose.blood.gas,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin
inpatient.number,,,,,,,,,,,,,,,,,,,,,
854186,37.5,100,19,144,71,95.333333,21.555556,2,4,2,...,2.551127,4.050462,107.302722,142.023506,5.274536,0.570702,94.339338,104.540602,96.494683,135.981778
833791,36.3,67,21,111,70,83.666667,16.646849,2,3,1,...,3.586095,3.820054,106.705178,140.599673,4.144149,0.436806,94.021851,103.974579,95.448468,169.715086
729910,36.8,102,19,110,60,76.666667,18.025957,0,3,2,...,2.743689,3.616304,108.024907,139.852575,5.888771,0.212442,95.631884,101.857404,95.497750,155.096455
838987,36.2,88,19,94,70,78.000000,19.628265,2,4,3,...,1.200000,4.670000,97.000000,120.800000,6.400000,0.500000,99.000000,151.000000,98.200000,116.000000
752180,36.5,90,20,130,60,83.333333,17.777778,2,4,2,...,1.500000,2.620000,90.000000,130.000000,6.500000,0.200000,99.000000,124.000000,98.000000,115.000000

In [9]:
df3=pd.read_csv(r"C:\Users\vinayak\minor_proj\collabRV\collabRV\Z_Current\Sets\drug_onehot_latest.csv",index_col=[0])
df3.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
inpatient.number,,,,,,,,,,,,,,,,,,
722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [10]:
q="Atorvastatin calcium tablet"
r="Isoprenaline Hydrochloride injection"
s="Digoxin tablet"

In [11]:
#df1.drop(['hydroxybutyrate.dehydrogenase.to.lactate.dehydrogenase','hydroxybutyrate.dehydrogenase','free.calcium','anion.gap','lactate.dehydrogenase','lactate','CCI.score','consciousness','eye.opening','verbal.response','respiratory.support.','gender','ageCat'],axis=1,inplace=True)

In [12]:
df2=df3[q]

In [13]:
df=pd.concat([df1,df2],axis=1)

In [14]:
cols_to_scale = [df.columns]

scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)

In [15]:
df = pd.DataFrame(scaled_df,columns = df.columns)

In [16]:
df

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,potassium.ion,chloride.ion,sodium.ion,glucose.blood.gas,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,Atorvastatin calcium tablet
0,0.271429,0.333333,0.500000,0.480159,0.383562,0.428309,0.046006,1.0,1.0,0.000000,...,0.462255,0.672512,0.747306,0.137840,0.140986,0.950984,0.316472,0.941277,0.686463,0.0
1,0.142857,0.363636,0.583333,0.595238,0.547945,0.569853,0.053564,1.0,1.0,0.000000,...,0.412078,0.750000,0.777215,0.085784,0.132075,0.880000,0.187234,0.878342,0.226190,1.0
2,0.200000,0.353535,0.555556,0.476190,0.547945,0.514706,0.076992,1.0,0.5,0.333333,...,0.365897,0.625000,0.678481,0.125000,0.000000,0.973333,0.365957,0.981283,0.410714,1.0
3,0.242857,0.651515,0.611111,0.484127,0.589041,0.540441,0.049828,1.0,0.5,0.666667,...,0.427526,0.652866,0.735337,0.113675,0.090877,0.934069,0.282782,0.957616,0.739584,0.0
4,0.271429,0.505051,0.555556,0.376984,0.445205,0.413603,0.054523,1.0,0.5,0.000000,...,0.418081,0.622484,0.904769,0.119964,0.094730,0.962117,0.326331,0.954084,0.605290,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,0.285714,0.464646,0.527778,0.634921,0.547945,0.588235,0.043996,0.0,1.0,0.333333,...,0.357016,0.625000,0.635443,0.313725,0.056604,0.986667,0.561702,0.987968,0.321429,0.0
1999,0.142857,0.303030,0.833333,0.678571,0.801370,0.744485,0.067515,1.0,0.5,0.333333,...,0.477119,0.627054,0.854731,0.125463,0.145465,0.940403,0.268889,0.958077,0.600442,0.0
2000,0.214286,0.494949,0.527778,0.674603,0.445205,0.551471,0.060653,1.0,0.5,0.333333,...,0.390764,0.729167,0.769620,0.198529,0.188679,0.560000,0.080851,0.557487,0.398810,1.0
2001,0.228571,0.545455,0.500000,0.555556,0.465753,0.507353,0.036393,1.0,0.5,0.333333,...,0.395402,0.564740,0.876270,0.114154,0.021828,0.922586,0.355247,0.959724,0.777988,0.0
2002,0.214286,0.570707,0.500000,0.575397,0.773973,0.681985,0.051504,1.0,1.0,0.333333,...,0.391512,0.653839,0.894766,0.140730,0.116521,0.966599,0.292782,0.956431,0.771919,1.0

In [17]:
#df.drop(['ageCat','gender'],axis=1,inplace=True)

# the ANN Function for atorvostatin

In [19]:
def ANN(X_train, y_train, X_test, y_test, loss, weights):
    model = keras.Sequential([
        
        keras.layers.Dense(65, input_dim=46, activation='relu'),
        keras.layers.Dropout(0.2),
        #keras.layers.Dense(25, input_dim=51, activation='relu'),
        keras.layers.Dense(15, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='rmsprop', loss=loss, metrics=['accuracy'])
    
    if weights == -1:
        model.fit(X_train, y_train, epochs=100)
    else:
        model.fit(X_train, y_train, epochs=100, class_weight = weights)
    
    print(model.evaluate(X_test, y_test))
    
    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)
    
    print("Classification Report: \n", classification_report(y_test, y_preds))
    
    return y_preds

# Principle Component Analysis

In [20]:
X = df.drop(q,axis='columns')
y = df[q]

In [21]:
X

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,reduced.hemoglobin,potassium.ion,chloride.ion,sodium.ion,glucose.blood.gas,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin
0,0.271429,0.333333,0.500000,0.480159,0.383562,0.428309,0.046006,1.0,1.0,0.000000,...,0.030435,0.462255,0.672512,0.747306,0.137840,0.140986,0.950984,0.316472,0.941277,0.686463
1,0.142857,0.363636,0.583333,0.595238,0.547945,0.569853,0.053564,1.0,1.0,0.000000,...,0.116935,0.412078,0.750000,0.777215,0.085784,0.132075,0.880000,0.187234,0.878342,0.226190
2,0.200000,0.353535,0.555556,0.476190,0.547945,0.514706,0.076992,1.0,0.5,0.333333,...,0.022849,0.365897,0.625000,0.678481,0.125000,0.000000,0.973333,0.365957,0.981283,0.410714
3,0.242857,0.651515,0.611111,0.484127,0.589041,0.540441,0.049828,1.0,0.5,0.666667,...,0.008432,0.427526,0.652866,0.735337,0.113675,0.090877,0.934069,0.282782,0.957616,0.739584
4,0.271429,0.505051,0.555556,0.376984,0.445205,0.413603,0.054523,1.0,0.5,0.000000,...,0.010983,0.418081,0.622484,0.904769,0.119964,0.094730,0.962117,0.326331,0.954084,0.605290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,0.285714,0.464646,0.527778,0.634921,0.547945,0.588235,0.043996,0.0,1.0,0.333333,...,0.010753,0.357016,0.625000,0.635443,0.313725,0.056604,0.986667,0.561702,0.987968,0.321429
1999,0.142857,0.303030,0.833333,0.678571,0.801370,0.744485,0.067515,1.0,0.5,0.333333,...,0.047049,0.477119,0.627054,0.854731,0.125463,0.145465,0.940403,0.268889,0.958077,0.600442
2000,0.214286,0.494949,0.527778,0.674603,0.445205,0.551471,0.060653,1.0,0.5,0.333333,...,0.430108,0.390764,0.729167,0.769620,0.198529,0.188679,0.560000,0.080851,0.557487,0.398810
2001,0.228571,0.545455,0.500000,0.555556,0.465753,0.507353,0.036393,1.0,0.5,0.333333,...,0.050461,0.395402,0.564740,0.876270,0.114154,0.021828,0.922586,0.355247,0.959724,0.777988
2002,0.214286,0.570707,0.500000,0.575397,0.773973,0.681985,0.051504,1.0,1.0,0.333333,...,0.030715,0.391512,0.653839,0.894766,0.140730,0.116521,0.966599,0.292782,0.956431,0.771919

In [22]:
y.to_frame()

      Atorvastatin calcium tablet
0                             0.0
1                             1.0
2                             1.0
3                             0.0
4                             0.0
...                           ...
1998                          0.0
1999                          0.0
2000                          1.0
2001                          0.0
2002                          1.0

[2003 rows x 1 columns]

In [23]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df = pd.concat([PCA_df, df[q]], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,Atorvastatin calcium tablet
0,0.485152,-0.268583,-0.507123,0.513626,-0.233606,0.030368,0.058925,-0.343838,0.243563,0.286981,...,0.081991,0.090898,-0.017447,0.121411,-0.015282,0.080368,-0.118612,-0.045980,-0.011813,0.0
1,-0.145042,-0.353461,-0.183404,-0.139457,-0.245284,-0.129782,0.252421,-0.349743,0.220273,0.805366,...,-0.099277,0.057628,0.085873,-0.022387,-0.130570,0.083693,0.089900,0.141666,0.119717,1.0
2,-0.173621,-0.210423,-0.200054,-0.314970,0.105571,-0.199907,-0.110117,0.278727,-0.162158,0.274271,...,-0.130396,-0.007525,0.038919,-0.133981,0.069500,0.077070,0.069247,-0.060637,-0.157007,1.0
3,0.396161,-0.094074,-0.584406,0.188463,0.424859,0.632022,-0.447740,-0.320468,0.039108,-0.089374,...,-0.076964,0.109443,-0.010140,0.230267,0.041187,-0.201982,0.065821,-0.019499,-0.062648,0.0
4,-0.427098,-0.211032,0.043938,0.211464,-0.214811,-0.171968,-0.411327,-0.091980,0.044690,-0.117016,...,0.027913,-0.207839,0.081620,0.099522,-0.040893,0.002526,0.224720,0.039183,-0.006331,0.0

# OverSampling

In [24]:
count_class_0, count_class_1 = PCA_df[q].value_counts()[0], PCA_df[q].value_counts()[1]
# Divide by class
df_class_0 = PCA_df[PCA_df[q] == 0]
df_class_1 = PCA_df[PCA_df[q] == 1]

In [25]:
PCA_df[q].value_counts(ascending =True)

1.0     818
0.0    1185
Name: Atorvastatin calcium tablet, dtype: int64

In [26]:
PCA_df[q].value_counts()

0.0    1185
1.0     818
Name: Atorvastatin calcium tablet, dtype: int64

In [27]:
# Oversample 1-class and concat the DataFrames of both classes( if count of 0 greater than count of 1)
# Oversample 0-class and concat the DataFrames of both classes( if count of 0 lesser than count of 1)
if count_class_0>count_class_1:
    df_class_1_over = df_class_1.sample(count_class_0, replace=True)
    df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

    print('Random over-sampling:')
    print(df_test_over[q].value_counts())
else:
    df_class_0_over = df_class_0.sample(count_class_1,replace=True)
    df_test_over = pd.concat([df_class_0_over, df_class_1], axis=0)

    print('Random over-sampling:')
    print(df_test_over[q].value_counts())

Random over-sampling:
0.0    1185
1.0    1185
Name: Atorvastatin calcium tablet, dtype: int64

In [28]:
X = df_test_over.drop(q,axis='columns')
y = df_test_over[q]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [29]:
# Number of classes in training Data
y_train.value_counts()

0.0    948
1.0    948
Name: Atorvastatin calcium tablet, dtype: int64

In [35]:
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.datasets import make_classification

In [45]:
>>> clf = RandomForestClassifier(max_depth=100, random_state=0)
>>> clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=100, random_state=0)

In [46]:
clf.score(X_test,y_test)

0.7911392405063291

In [47]:
y_preds = clf.predict(X_test)
y_preds = np.round(y_preds)

print("Classification Report: \n", classification_report(y_test, y_preds))

Classification Report:
               precision    recall  f1-score   support

         0.0       0.76      0.85      0.80       237
         1.0       0.83      0.73      0.78       237

    accuracy                           0.79       474
   macro avg       0.79      0.79      0.79       474
weighted avg       0.79      0.79      0.79       474

# Isoprenaline and Dobutamine

In [48]:
df2=df3[r]
df=pd.concat([df1,df2],axis=1)
cols_to_scale = [df.columns]
scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)
df = pd.DataFrame(scaled_df,columns = df.columns)

In [49]:
def ANN2(X_train, y_train, X_test, y_test, loss, weights):
    model = keras.Sequential([
        keras.layers.Dropout(0.2),
        keras.layers.Dense(65, input_dim=65, activation='relu'),
        keras.layers.Dropout(0.2),
        #keras.layers.Dense(25, input_dim=51, activation='relu'),
        #keras.layers.Dense(15, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='rmsprop', loss=loss, metrics=['accuracy'])
    
    if weights == -1:
        model.fit(X_train, y_train, epochs=50)
    else:
        model.fit(X_train, y_train, epochs=50, class_weight = weights)
    
    print(model.evaluate(X_test, y_test))
    
    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)
    
    print("Classification Report: \n", classification_report(y_test, y_preds))
    
    return y_preds

In [50]:
X = df.drop(r,axis='columns')
y = df[r]

In [51]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df = pd.concat([PCA_df, df[r]], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,Isoprenaline Hydrochloride injection
0,0.485152,-0.268583,-0.507123,0.513626,-0.233606,0.030368,0.058925,-0.343838,0.243563,0.286981,...,0.081991,0.090898,-0.017447,0.121411,-0.015282,0.080368,-0.118612,-0.045980,-0.011813,0.0
1,-0.145042,-0.353461,-0.183404,-0.139457,-0.245284,-0.129782,0.252421,-0.349743,0.220273,0.805366,...,-0.099277,0.057628,0.085873,-0.022387,-0.130570,0.083693,0.089900,0.141666,0.119717,0.0
2,-0.173621,-0.210423,-0.200054,-0.314970,0.105571,-0.199907,-0.110117,0.278727,-0.162158,0.274271,...,-0.130396,-0.007525,0.038919,-0.133981,0.069500,0.077070,0.069247,-0.060637,-0.157007,0.0
3,0.396161,-0.094074,-0.584406,0.188463,0.424859,0.632022,-0.447740,-0.320468,0.039108,-0.089374,...,-0.076964,0.109443,-0.010140,0.230267,0.041187,-0.201982,0.065821,-0.019499,-0.062648,0.0
4,-0.427098,-0.211032,0.043938,0.211464,-0.214811,-0.171968,-0.411327,-0.091980,0.044690,-0.117016,...,0.027913,-0.207839,0.081620,0.099522,-0.040893,0.002526,0.224720,0.039183,-0.006331,0.0

In [52]:
count_class_0, count_class_1 = PCA_df[r].value_counts()[0], PCA_df[r].value_counts()[1]
# Divide by class
df_class_0 = PCA_df[PCA_df[r] == 0]
df_class_1 = PCA_df[PCA_df[r] == 1]

In [53]:
PCA_df[r].value_counts(ascending =True)

1.0      30
0.0    1973
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [54]:
# Oversample 1-class and concat the DataFrames of both classes( if count of 0 greater than count of 1)
# Oversample 0-class and concat the DataFrames of both classes( if count of 0 lesser than count of 1)
if count_class_0>count_class_1:
    df_class_1_over = df_class_1.sample(count_class_0, replace=True)
    df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

    print('Random over-sampling:')
    print(df_test_over[r].value_counts())
else:
    df_class_0_over = df_class_0.sample(count_class_1,replace=True)
    df_test_over = pd.concat([df_class_0_over, df_class_1], axis=0)

    print('Random over-sampling:')
    print(df_test_over[r].value_counts())

Random over-sampling:
0.0    1973
1.0    1973
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [55]:
X = df_test_over.drop(r,axis='columns')
y = df_test_over[r]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [56]:
y_train.value_counts()

0.0    1578
1.0    1578
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [57]:
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.datasets import make_classification

# Digoxin

In [513]:
df2=df3[s]
df=pd.concat([df1,df2],axis=1)
cols_to_scale = [df.columns]

scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)
df = pd.DataFrame(scaled_df,columns = df.columns)

In [640]:
def ANN3(X_train, y_train, X_test, y_test, loss, weights):
    model = keras.Sequential([
        keras.layers.Dense(65,input_dim=65, activation='relu'),
        #keras.layers.Dense(25, input_dim=51, activation='relu'),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(15, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='rmsprop', loss=loss, metrics=['accuracy'])
    
    if weights == -1:
        model.fit(X_train, y_train, epochs=50)
    else:
        model.fit(X_train, y_train, epochs=50, class_weight = weights)
    
    print(model.evaluate(X_test, y_test))
    
    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)
    
    print("Classification Report: \n", classification_report(y_test, y_preds))
    
    return y_preds

In [641]:
X = df.drop(s,axis='columns')
y = df[s]

In [642]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df = pd.concat([PCA_df, df[s]], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,Digoxin tablet
0,-0.572855,0.775703,-0.555175,-0.668609,0.206971,0.311069,0.004777,-0.218921,0.021354,0.522483,...,0.117052,0.313998,0.083378,0.270367,0.613181,-0.032338,-0.291381,-0.346303,-0.057003,1.0
1,0.378881,-0.054257,-0.140639,-0.745776,0.054000,-0.078432,0.065719,-0.312667,-0.300151,0.531537,...,0.130041,-0.281455,-0.216349,0.080771,0.129352,0.079545,-0.117099,0.032437,0.089642,1.0
2,0.378855,-0.298639,-0.214987,-0.136841,-0.174487,0.944021,0.676052,0.005444,0.292429,-0.035979,...,0.162750,0.056158,0.233953,0.037804,-0.182907,0.073337,0.190404,0.210340,-0.395110,0.0
3,-0.385298,0.650624,-0.147322,-0.262479,0.156089,0.317733,-0.001556,-0.057074,0.389654,0.725043,...,-0.025797,0.037880,0.050543,0.093189,0.009083,0.240156,-0.030918,0.150497,-0.147013,1.0
4,-0.721262,-0.141627,0.296722,0.191071,-0.157643,-0.106280,0.209430,0.399258,-0.148421,0.039294,...,-0.083293,0.046128,-0.067033,0.065144,0.102891,0.149844,0.059303,-0.015103,-0.049884,1.0

In [643]:
count_class_0, count_class_1 = PCA_df[s].value_counts()[0], PCA_df[s].value_counts()[1]
# Divide by class
df_class_0 = PCA_df[PCA_df[s] == 0]
df_class_1 = PCA_df[PCA_df[s] == 1]

In [644]:
PCA_df[s].value_counts(ascending =True)

1.0     997
0.0    1006
Name: Digoxin tablet, dtype: int64

In [645]:
# Oversample 1-class and concat the DataFrames of both classes( if count of 0 greater than count of 1)
# Oversample 0-class and concat the DataFrames of both classes( if count of 0 lesser than count of 1)
if count_class_0>count_class_1:
    df_class_1_over = df_class_1.sample(count_class_0, replace=True)
    df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

    print('Random over-sampling:')
    print(df_test_over[s].value_counts())
else:
    df_class_0_over = df_class_0.sample(count_class_1,replace=True)
    df_test_over = pd.concat([df_class_0_over, df_class_1], axis=0)

    print('Random over-sampling:')
    print(df_test_over[s].value_counts())

Random over-sampling:
0.0    1006
1.0    1006
Name: Digoxin tablet, dtype: int64

In [646]:
X = df_test_over.drop(s,axis='columns')
y = df_test_over[s]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=15, stratify=y)

In [647]:
y_train.value_counts()

0.0    704
1.0    704
Name: Digoxin tablet, dtype: int64

In [648]:
loss = keras.losses.BinaryCrossentropy()
weights = -1
y_preds = ANN3(X_train, y_train, X_test, y_test, 'binary_crossentropy', -1)

Epoch 1/50
44/44 [==============================] - 1s 1ms/step - loss: 0.6892 - accuracy: 0.5348
Epoch 2/50
44/44 [==============================] - 0s 1ms/step - loss: 0.6569 - accuracy: 0.6151
Epoch 3/50
44/44 [==============================] - 0s 1ms/step - loss: 0.6386 - accuracy: 0.6548
Epoch 4/50
44/44 [==============================] - 0s 1ms/step - loss: 0.6083 - accuracy: 0.6932
Epoch 5/50
44/44 [==============================] - 0s 1ms/step - loss: 0.5814 - accuracy: 0.7216
Epoch 6/50
44/44 [==============================] - 0s 1ms/step - loss: 0.5608 - accuracy: 0.7230
Epoch 7/50
44/44 [==============================] - 0s 2ms/step - loss: 0.5548 - accuracy: 0.7251
Epoch 8/50
44/44 [==============================] - 0s 2ms/step - loss: 0.5305 - accuracy: 0.7450
Epoch 9/50
44/44 [==============================] - 0s 2ms/step - loss: 0.5262 - accuracy: 0.7472
Epoch 10/50
44/44 [==============================] - 0s 1ms/step - loss: 0.5073 - accuracy: 0.7592
Epoch 11/50
44/44 [==============================] - 0s 2ms/step - loss: 0.5089 - accuracy: 0.7607
Epoch 12/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4880 - accuracy: 0.7720
Epoch 13/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4779 - accuracy: 0.7940
Epoch 14/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4690 - accuracy: 0.7827
Epoch 15/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4618 - accuracy: 0.7876
Epoch 16/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4483 - accuracy: 0.8040
Epoch 17/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4374 - accuracy: 0.8104
Epoch 18/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4337 - accuracy: 0.8175
Epoch 19/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4151 - accuracy: 0.8317
Epoch 20/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4135 - accuracy: 0.8153
Epoch 21/50
44/44 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.8260
Epoch 22/50
44/44 [==============================] - 0s 1ms/step - loss: 0.4003 - accuracy: 0.8281
Epoch 23/50
44/44 [==============================] - 0s 1ms/step - loss: 0.3804 - accuracy: 0.8416
Epoch 24/50
44/44 [==============================] - 0s 1ms/step - loss: 0.3783 - accuracy: 0.8416
Epoch 25/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3792 - accuracy: 0.8381
Epoch 26/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3659 - accuracy: 0.8466
Epoch 27/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3505 - accuracy: 0.8615
Epoch 28/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3416 - accuracy: 0.8601
Epoch 29/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8509
Epoch 30/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.8700
Epoch 31/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3253 - accuracy: 0.8750
Epoch 32/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3132 - accuracy: 0.8729
Epoch 33/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3244 - accuracy: 0.8629
Epoch 34/50
44/44 [==============================] - 0s 2ms/step - loss: 0.3001 - accuracy: 0.8864
Epoch 35/50
44/44 [==============================] - 0s 1ms/step - loss: 0.2960 - accuracy: 0.8778
Epoch 36/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2903 - accuracy: 0.8764
Epoch 37/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2818 - accuracy: 0.8807
Epoch 38/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2717 - accuracy: 0.8949
Epoch 39/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2593 - accuracy: 0.8928
Epoch 40/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2704 - accuracy: 0.8892
Epoch 41/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2521 - accuracy: 0.9070
Epoch 42/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2378 - accuracy: 0.9169
Epoch 43/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2547 - accuracy: 0.9062
Epoch 44/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2432 - accuracy: 0.8984
Epoch 45/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2359 - accuracy: 0.9105
Epoch 46/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2343 - accuracy: 0.9098
Epoch 47/50
44/44 [==============================] - 0s 1ms/step - loss: 0.2404 - accuracy: 0.9048
Epoch 48/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2227 - accuracy: 0.9148
Epoch 49/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2179 - accuracy: 0.9197
Epoch 50/50
44/44 [==============================] - 0s 2ms/step - loss: 0.2035 - accuracy: 0.9212
19/19 [==============================] - 0s 1ms/step - loss: 0.7900 - accuracy: 0.7252
[0.7900398969650269, 0.7251655459403992]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.73      0.72      0.72       302
         1.0       0.72      0.74      0.73       302

    accuracy                           0.73       604
   macro avg       0.73      0.73      0.73       604
weighted avg       0.73      0.73      0.73       604