In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df1 = pd.read_csv("random_imputed.csv",index_col=[0])
df1.sample(5)

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
inpatient.number,,,,,,,,,,,,,,,,,,,,,
755423,0,36.0,70,18,118,84,95.333333,21.428571,2,3,...,29.200000,0.300000,99.000000,127.000000,98.100000,8.20000,1.170000,114.000000,15,85
809124,0,36.3,80,18,124,86,98.666667,23.437500,0,3,...,20.700000,0.300000,96.000000,85.000000,95.700000,10.00000,1.130000,134.000000,15,65
743698,0,36.1,60,18,100,60,73.333333,24.000000,2,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,35
790132,1,36.5,103,18,118,62,80.666667,19.031142,0,4,...,30.900000,2.610000,69.730000,54.000000,68.610000,13.70000,1.150000,161.000000,15,45
802445,0,36.7,94,19,152,68,96.000000,17.777778,0,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,85

In [3]:
df1.drop(['hydroxybutyrate.dehydrogenase.to.lactate.dehydrogenase','hydroxybutyrate.dehydrogenase','free.calcium','anion.gap','lactate.dehydrogenase','lactate','CCI.score','consciousness','eye.opening','verbal.response','respiratory.support.','gender','ageCat'],axis=1,inplace=True)

In [ ]:
['oxygen.inhalation','Chronic.obstructive.pulmonary.disease','leukemia','AIDS','coefficient.of.variation.of.red.blood.cell.distribution.width','standard.deviation.of.red.blood.cell.distribution.width','lymphocyte.count']

In [4]:
len(df1.columns)

116

In [12]:
df1.var()

body.temperature              0.287044
pulse                       442.312921
respiration                   4.776789
systolic.blood.pressure     611.817676
diastolic.blood.pressure    209.232184
                               ...
oxygen.saturation            21.392268
partial.oxygen.pressure     699.044935
oxyhemoglobin                29.171025
total.hemoglobin            373.292621
GCS                           1.395417
Length: 116, dtype: float64

In [11]:
for x in df1.var():
    print(x)

0.2870444393669255
442.3129207287969
4.776789361412426
611.8176760832775
209.2321841912456
244.0792295841731
15.051090583731277
0.7266452967900796
0.46539930364193965
0.5778500082044765
0.06547172248620077
0.06331960600557705
0.04790566398155015
0.06931411075195398
0.05414455738968969
0.10284523265052473
0.0019940119790344455
0.021972535701941596
0.1772720539570265
0.1802072116600324
0.0059580958232980175
0.0
0.0004992511233150276
0.019101218302416498
0.040198443593351244
0.0019940119790344455
0.0537021640366623
0.30137760392378476
0.051927603100843225
22.678242875447072
0.002988025454326004
76.9410534297039
610.099466505353
33.69234567117199
10521.32392553038
36.1507467910242
28004.102169135433
1235.3679078121002
1.02790245198668
13.445495024156752
0.44921664781978926
0.060625215628833364
0.5427827536078994
5.524357590257284
44.51788436416887
88.56757205575119
29.1401060784302
0.38176362764100724
13.709050115157842
192.237611722671
3.8904675104333366
0.008444575787398408
0.0007006764485177646
0.2989799817319341
0.07428870591669885
587.917901871249
4192.286555776082
4.311949141143358
0.00401277464488412
0.011043313018559243
12.618060242548681
36.117555075375165
0.49551549726977717
53.805206436047854
3.5708338613610553
325.96122472953647
1.1438613965255573
2.4493680653020733
21.50028773798236
0.029762454935677106
0.47809075348028773
35.24345972264931
24.68541168829813
0.030853982855151205
39018.60697665042
32324.148817904712
274.72501394133405
1946103.7209908778
1279.463619975557
16.582770866413842
98.10979472924782
25.07031187896996
0.08556802148163124
6700.810087425965
74771.48980550068
78.86945485069363
1913.020199595572
33.71568022510068
112.04738850553927
334.7486732554216
256.45777021622183
48.88765558816312
1.0241133429674198
0.7939296861392171
0.7011553987457229
0.15593821227362142
0.0038380208871849663
16.70172640194619
8.55318445263421
52.18746043063256
18.468138265607703
5.642337207990118
354.23547048550716
28.273510519854327
0.22255649736149577
20.4357537525418
31.19711974758601
13.063391072295154
13.578584512314322
11.391411108163926
0.25133204125129854
21.392267517649934
699.0449351228488
29.17102513415481
373.2926206676844
1.3954173634652915