In [1]:
# All the libraries you'll need( probably)
import pandas as pd
import numpy as np 
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv(r"reduced_col.csv",index_col=[0])

In [3]:
df.head()

,gender,body.temperature,pulse,respiration,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,myocardial.infarction,...,methemoglobin,chloride.ion,glucose.blood.gas,lactate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,anion.gap,free.calcium,ageCat
0,0.0,0.271429,0.333333,0.500000,0.428309,0.046006,1.0,1.0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667
1,0.0,0.142857,0.363636,0.583333,0.569853,0.053564,1.0,1.0,0.000000,0.0,...,0.130435,0.750,0.085784,0.109756,0.132075,0.880000,0.187234,0.394444,0.44,0.533333
2,1.0,0.200000,0.353535,0.555556,0.514706,0.076992,1.0,0.5,0.333333,0.0,...,0.130435,0.625,0.125000,0.085366,0.000000,0.973333,0.365957,0.286111,0.44,0.800000
3,1.0,0.242857,0.651515,0.611111,0.540441,0.049828,1.0,0.5,0.666667,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667
4,0.0,0.271429,0.505051,0.555556,0.413603,0.054523,1.0,0.5,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.266667

In [4]:
df.drop(['gender'],axis=1,inplace=True)

In [8]:
import sklearn.impute

In [9]:
# knn imputation transform for the horse colic dataset
from numpy import isnan
from pandas import read_csv
from sklearn.impute import KNNImputer

In [10]:
imputer = KNNImputer(n_neighbors=30, weights='uniform', metric='nan_euclidean')

In [11]:
xtrans = imputer.fit_transform(df)

In [12]:
xtrans.shape

(1996, 99)

In [13]:
df2 =pd.read_csv(r'C:\Users\Vinayak\minor_proj\collabRV\EDA\drug_dict_onehot.csv',index_col=[0])
df2.head()

,inpatient.number,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
0,722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
1,723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
2,723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
4,725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [14]:
df2.drop(['inpatient.number'],axis=1,inplace=True)
df2.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
0,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
1,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
4,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [15]:
df3=df2['Atorvastatin calcium tablet']
df3 = df3.to_frame()

In [16]:
df3.shape

(1996, 1)

In [17]:
df_trans = pd.DataFrame(xtrans, columns =df.columns)

In [18]:
X = df_trans
y = df3

In [116]:
from imblearn.over_sampling import SMOTE
os = SMOTE(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# columns = X_train.columns
# os_data_X,os_data_y=os.fit_resample(X_train, y_train)
# os_data_X = pd.DataFrame(data=os_data_X,columns=columns )
# os_data_y= pd.DataFrame(data=os_data_y,columns=['y'])
# # we can Check the numbers of our data
# print("length of oversampled data is ",len(os_data_X))
# print("Number of no subscription in oversampled data",len(os_data_y[os_data_y['y']==0]))
# print("Number of subscription",len(os_data_y[os_data_y['y']==1]))
# print("Proportion of no subscription data in oversampled data is ",len(os_data_y[os_data_y['y']==0])/len(os_data_X))
# print("Proportion of subscription data in oversampled data is ",len(os_data_y[os_data_y['y']==1])/len(os_data_X))

In [117]:
logreg = LogisticRegression()
rfe = RFE(logreg,step = 20)
rfe = rfe.fit(X_train, y_train.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

[ True  True  True  True False False False  True False  True False False
 False False  True  True False False False  True False  True  True False
 False  True False  True False  True  True False False False False  True
 False  True False  True  True  True False False  True  True False False
  True  True  True False  True  True False  True  True  True  True False
  True False  True False False False  True  True  True False  True  True
 False  True False  True False  True False False  True False False False
 False False False  True False  True  True False False  True  True False
 False  True  True]
[1 1 1 1 3 4 4 1 3 1 3 3 3 4 1 1 2 4 2 1 4 1 1 3 2 1 2 1 4 1 1 3 4 2 4 1 4
 1 3 1 1 1 2 4 1 1 4 3 1 1 1 3 1 1 3 1 1 1 1 3 1 2 1 3 4 4 1 1 1 4 1 1 3 1
 3 1 3 1 3 4 1 4 4 3 2 3 4 1 2 1 1 4 2 1 1 3 4 1 1]

In [118]:
columns_to_remove = df.columns.values[np.logical_not(rfe.support_)]

In [119]:
columns_to_remove

array(['BMI', 'type.of.heart.failure',
       'NYHA.cardiac.function.classification', 'myocardial.infarction',
       'peripheral.vascular.disease', 'cerebrovascular.disease',
       'dementia', 'Chronic.obstructive.pulmonary.disease', 'diabetes',
       'moderate.to.severe.chronic.kidney.disease', 'hemiplegia',
       'solid.tumor', 'CCI.score', 'type.II.respiratory.failure',
       'respiratory.support.', 'fio2', 'mitral.valve.EMS',
       'tricuspid.valve.return.velocity',
       'outcome.during.hospitalization',
       'return.to.emergency.department.within.6.months', 'urea',
       'glomerular.filtration.rate', 'monocyte.count',
       'coefficient.of.variation.of.red.blood.cell.distribution.width',
       'mean.hemoglobin.volume', 'mean.hemoglobin.concentration',
       'hemoglobin', 'neutrophil.ratio', 'prothrombin.time.ratio',
       'high.sensitivity.troponin', 'potassium', 'sodium',
       'creatine.kinase.isoenzyme.to.creatine.kinase',
       'lactate.dehydrogenase', 'nucleotidase', 'albumin',
       'glutamyltranspeptidase', 'alkaline.phosphatase', 'globulin',
       'total.bile.acid', 'total.protein', 'cholesterol', 'triglyceride',
       'high.density.lipoprotein.cholesterol', 'pH',
       'partial.pressure.of.carbon.dioxide', 'glucose.blood.gas',
       'lactate', 'partial.oxygen.pressure', 'anion.gap'], dtype=object)

In [120]:
len(columns_to_remove)

50

In [121]:
X_train = X_train.drop(columns = columns_to_remove)
X_test = X_test.drop(columns = columns_to_remove)

In [122]:
X_train

,body.temperature,pulse,respiration,map,Killip.grade,congestive.heart.failure,connective.tissue.disease,peptic.ulcer.disease,malignant.lymphoma,liver.disease,...,white.globulin.ratio,glutamic.pyruvic.transaminase,total.bilirubin,standard.residual.base,methemoglobin,chloride.ion,carboxyhemoglobin,oxygen.saturation,free.calcium,ageCat
1528,0.171429,0.474747,0.500000,0.514706,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.480000,0.001218,0.054118,0.529167,0.131884,0.663889,0.081761,0.934667,0.498667,0.666667
1698,0.185714,0.434343,0.527778,0.551471,0.000000,1.0,0.0,0.0,0.0,0.0,...,0.560000,0.009340,0.048235,0.531539,0.085507,0.686111,0.117610,0.955556,0.477333,0.666667
638,0.214286,0.459596,0.583333,0.566176,0.666667,1.0,0.0,0.0,0.0,0.0,...,0.520000,0.002437,0.065490,0.557292,0.347826,0.687500,0.056604,0.973333,0.620000,0.800000
482,0.171429,0.464646,0.527778,0.569853,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.720000,0.003249,0.054902,0.548611,0.130435,0.708333,0.056604,0.960000,0.540000,0.666667
616,0.271429,0.383838,0.527778,0.606618,0.000000,1.0,0.0,0.0,0.0,0.0,...,0.640000,0.004061,0.049804,0.546933,0.100000,0.648611,0.119497,0.958222,0.438000,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,0.214286,0.616162,0.527778,0.386029,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.540000,0.027844,0.105987,0.499769,0.108696,0.688889,0.122642,0.949333,0.432667,0.533333
1216,0.214286,0.318182,0.500000,0.378676,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.600000,0.007716,0.043922,0.489294,0.095652,0.682639,0.084277,0.946667,0.451333,0.666667
1653,0.200000,0.555556,0.527778,0.522059,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.640000,0.019898,0.068235,0.519097,0.043478,0.687500,0.094340,0.946667,0.500000,0.400000
559,0.214286,0.570707,0.555556,0.459559,0.333333,1.0,0.0,0.0,0.0,0.0,...,0.490667,0.007195,0.107359,0.527778,0.000000,0.416667,0.056604,0.960000,0.400000,0.666667
684,0.228571,0.348485,0.527778,0.455882,0.333333,0.0,0.0,0.0,0.0,0.0,...,0.520000,0.003046,0.257255,0.543229,0.104348,0.652778,0.089937,0.949778,0.432667,0.666667

In [123]:
# atorv_cols = X_train[columns_to_remove]
# atorv_cols

In [124]:
# atorv_cols  = atorv_cols.drop([0])

In [125]:
# atorv_cols

In [126]:
# import statsmodels.api as sm
# y_train = list(y_train)
# logit_model=sm.Logit(y_train,X_train)
# result=logit_model.fit()
# print(result.summary2())

In [127]:
y_train.head()

      Atorvastatin calcium tablet
1528                            0
1698                            1
638                             1
482                             1
616                             0

In [128]:
logreg = LogisticRegression(verbose=1)
logreg.fit(X_train, y_train)

C:\Users\Vikram\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

LogisticRegression(verbose=1)

In [129]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.60

In [143]:
model = Sequential()
model.add(Dense(64, input_dim=49, activation='relu'))
model.add(Dense(32,  activation='relu'))
model.add(Dense(16,  activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss=tf.compat.v1.losses.sigmoid_cross_entropy, metrics= ['accuracy','mse'],optimizer=tf.keras.optimizers.Adam(learning_rate=0.01))
#tf.nn.softmax_cross_entropy_with_logits
model.fit(X_train, y_train)

44/44 [==============================] - 1s 1ms/step - loss: 0.6986 - accuracy: 0.5863 - mse: 0.3945

In [144]:
model.evaluate(X_test,y_test)

19/19 [==============================] - 0s 942us/step - loss: 0.6931 - accuracy: 0.5910 - mse: 0.4090

[0.6931473016738892, 0.5909850001335144, 0.409015029668808]

In [24]:
#decision tree classifier

In [22]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score

In [23]:
rfe = RFE(estimator=DecisionTreeClassifier(), n_features_to_select=5)
model = DecisionTreeClassifier()
pipeline = Pipeline(steps=[('s',rfe),('m',model)])
# evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.523 (0.036)