## AutoKeras
* Using AutoK to find the best neural network

### Initialising data

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
import autokeras as ak

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
df1 = pd.read_csv("random_imputed.csv",index_col=[0])
df1.sample(5)

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
inpatient.number,,,,,,,,,,,,,,,,,,,,,
832886,0,36.0,61,18,130,84,99.333333,20.313380,2,3,...,24.0,1.1,98.0,116.0,96.6,15.0,1.12,134.0,15,55
786199,1,36.5,96,19,145,80,101.666667,20.077335,2,3,...,22.6,0.7,97.0,96.0,96.4,11.3,1.13,120.0,15,85
809536,1,37.0,80,18,140,80,100.000000,18.730489,2,3,...,22.9,0.6,95.0,78.0,93.9,7.7,1.11,124.0,15,75
834979,0,38.0,92,20,120,73,88.666667,18.314256,2,3,...,31.4,0.7,99.0,128.0,97.6,12.8,1.05,141.0,15,65
728787,1,36.2,100,22,118,80,92.666667,27.055151,2,3,...,18.0,0.7,99.0,208.0,98.1,20.4,1.05,179.0,13,85

In [9]:
df3=pd.read_csv("drug_onehot_latest.csv",index_col=[0])
df3.head()

,sulfotanshinone sodium injection,Furosemide tablet,Meglumine Adenosine Cyclophosphate for injection,Furosemide injection,Milrinone injection,Deslanoside injection,Torasemide tablet,Benazepril hydrochloride tablet,Atorvastatin calcium tablet,Digoxin tablet,Hydrochlorothiazide tablet,Spironolactone tablet,Valsartan Dispersible tablet,Dobutamine hydrochloride injection,Isoprenaline Hydrochloride injection,Nitroglycerin injection,Shenfu injection,Isosorbide Mononitrate Sustained Release tablet
inpatient.number,,,,,,,,,,,,,,,,,,
722128,0,1,0,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0
723327,0,1,0,1,1,1,1,0,1,1,0,1,1,0,0,0,0,1
723617,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0
724385,0,1,0,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0
725509,0,1,0,1,1,1,1,0,0,1,0,1,0,0,0,0,1,0

In [10]:
df2=df3['Atorvastatin calcium tablet']
df2 = df2.to_frame()

In [11]:
df2.head()

                  Atorvastatin calcium tablet
inpatient.number
722128                                      0
723327                                      1
723617                                      1
724385                                      0
725509                                      0

In [12]:
cols_to_scale = [df1.columns]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df1)

In [13]:
df = pd.DataFrame(scaled_df,columns = df1.columns)

In [14]:
df.head()

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
0,0.0,0.271429,0.333333,0.500000,0.480159,0.383562,0.428309,0.046006,1.0,1.0,...,0.418060,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.666667
1,0.0,0.142857,0.363636,0.583333,0.595238,0.547945,0.569853,0.053564,1.0,1.0,...,0.391813,0.132075,0.880000,0.187234,0.878342,0.316258,0.440000,0.226190,1.0,0.533333
2,1.0,0.200000,0.353535,0.555556,0.476190,0.547945,0.514706,0.076992,1.0,0.5,...,0.500975,0.000000,0.973333,0.365957,0.981283,0.229399,0.440000,0.410714,1.0,0.800000
3,1.0,0.242857,0.651515,0.611111,0.484127,0.589041,0.540441,0.049828,1.0,0.5,...,0.418060,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.666667
4,0.0,0.271429,0.505051,0.555556,0.376984,0.445205,0.413603,0.054523,1.0,0.5,...,0.418060,0.229624,0.954472,0.284024,0.941835,0.380276,0.724655,0.696010,1.0,0.266667

### First model
* No preprocessing or sampling (Accuracy:60%)

In [15]:
X = df
y = df2

In [17]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [18]:
model_search = ak.StructuredDataClassifier(max_trials=20)

In [19]:
model_search.fit(x=X_train, y = y_train)

Trial 20 Complete [00h 00m 26s]
val_accuracy: 0.6137930750846863

Best val_accuracy So Far: 0.6275861859321594
Total elapsed time: 00h 06m 40s
INFO:tensorflow:Oracle triggered exit

51/51 [==============================] - 2s 3ms/step - loss: 0.6984 - accuracy: 0.5437
INFO:tensorflow:Assets written to: .\structured_data_classifier\best_model\assets

In [20]:
model_search.fit(x = X_train, y = y_train)

In [22]:
loss , acc = model_search.evaluate(x = X_train, y = y_train, verbose= 0)
print(f"Train Accuracy = {acc}")

Accuracy = 0.6279650330543518

In [23]:
loss , acc = model_search.evaluate(x = X_test, y = y_test, verbose= 0)
print(f"Test Accuracy = {acc}")

Accuracy = 0.6059850454330444

### Second Model
*