In [3]:
# All the libraries you'll need( probably)
import pandas as pd
import numpy as np 
from numpy import mean
from numpy import std
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from sklearn.metrics import accuracy_score

In [5]:
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split

In [4]:
df1=pd.read_csv(r"reduced_col.csv",index_col=[0])

In [6]:
df1.head()

,gender,body.temperature,pulse,respiration,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,myocardial.infarction,...,methemoglobin,chloride.ion,glucose.blood.gas,lactate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,anion.gap,free.calcium,ageCat
0,0.0,0.271429,0.333333,0.500000,0.428309,0.046006,1.0,1.0,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667
1,0.0,0.142857,0.363636,0.583333,0.569853,0.053564,1.0,1.0,0.000000,0.0,...,0.130435,0.750,0.085784,0.109756,0.132075,0.880000,0.187234,0.394444,0.44,0.533333
2,1.0,0.200000,0.353535,0.555556,0.514706,0.076992,1.0,0.5,0.333333,0.0,...,0.130435,0.625,0.125000,0.085366,0.000000,0.973333,0.365957,0.286111,0.44,0.800000
3,1.0,0.242857,0.651515,0.611111,0.540441,0.049828,1.0,0.5,0.666667,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667
4,0.0,0.271429,0.505051,0.555556,0.413603,0.054523,1.0,0.5,0.000000,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.266667

In [26]:
df1.drop(['gender'],axis=1,inplace=True)

In [11]:
df2 =pd.read_csv(r'C:\Users\vinayak\minor_proj\collabRV\EDA\drug_dict_onehot.csv',index_col=[0])
df2.head()

,inpatient.number,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
0,722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
1,723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
2,723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
4,725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [12]:
df2.drop(['inpatient.number'],axis=1,inplace=True)
df2.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
0,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
1,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
2,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
4,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [22]:
df3=df2['Atorvastatin calcium tablet']
df3 = df3.to_frame()

In [23]:
df3.head()

   Atorvastatin calcium tablet
0                            0
1                            1
2                            1
3                            0
4                            0

In [24]:
#Lets try and train the model against just one tablet
#i will use XGBoost that tests the best way of imputation and does it

In [27]:
import xgboost as xgb

In [35]:
X_train, X_test, y_train, y_test = train_test_split(df1, df3,test_size=0.3, random_state=1121218)

In [40]:
xgb_cl= xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

In [41]:
xgb_cl.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              eval_metric='mlogloss', gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [42]:
preds = xgb_cl.predict(X_test)

In [44]:
accuracy_score(y_test, preds)

0.5525876460767947

In [47]:

param_grid = {
    "max_depth": [3, 4, 5, 7],
    "learning_rate": [0.1, 0.01, 0.05],
    "gamma": [0, 0.25, 1],
    "reg_lambda": [0, 1, 10],
    "scale_pos_weight": [1, 3, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.5],
}

In [49]:
from sklearn.model_selection import GridSearchCV

# Init classifier
xgb_cl = xgb.XGBClassifier(objective="binary:logistic")

# Init Grid Search
grid_cv = GridSearchCV(xgb_cl,param_grid, n_jobs=-1, cv=3, scoring="roc_auc")

# Fit
_ = grid_cv.fit(X_train, y_train)

E:\anoconda\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
E:\anoconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

[17:19:32] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [50]:
grid_cv.best_score_

0.5708130429873727

In [51]:
grid_cv.best_params_

{'colsample_bytree': 0.5,
 'gamma': 0.25,
 'learning_rate': 0.1,
 'max_depth': 3,
 'reg_lambda': 10,
 'scale_pos_weight': 1,
 'subsample': 0.8}

In [52]:
#Some parameters are at the end of their ranges meaning that we have to keep exploring:

In [53]:
# Insert the new fixed values to the grid
param_grid["scale_pos_weight"] = [3]
param_grid["subsample"] = [0.8]
param_grid["colsample_bytree"] = [0.5]
param_grid["gamma"] = [0.25]

# Give new value ranges to other params
param_grid["max_depth"] = [1,2,3]
param_grid["reg_lambda"] = [10, 30, 50]
param_grid["learning_rate"] = [0.2,0.3, 0.5, 0.7, 1]

In [55]:
grid_cv_2 = GridSearchCV(xgb_cl, param_grid, 
                         cv=3, scoring="roc_auc", n_jobs=-1)

_ = grid_cv_2.fit(X_train, y_train)

E:\anoconda\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
E:\anoconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

[17:30:38] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [56]:
grid_cv_2.best_score_

0.5812413457364677

In [57]:
grid_cv.best_params_

{'colsample_bytree': 0.5,
 'gamma': 0.25,
 'learning_rate': 0.1,
 'max_depth': 3,
 'reg_lambda': 10,
 'scale_pos_weight': 1,
 'subsample': 0.8}