# Importing Libraries

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix , classification_report

In [3]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df1 = pd.read_csv("random_imputed.csv",index_col=[0])
df1.sample(5)

,gender,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,...,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,anion.gap,free.calcium,total.hemoglobin,GCS,ageCat
inpatient.number,,,,,,,,,,,,,,,,,,,,,
736358,0,36.3,93,18,164,78,106.666667,19.531250,2,2,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,75
859681,0,36.5,120,19,130,80,96.666667,22.829964,2,4,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,75
736762,1,36.2,98,19,110,70,83.333333,23.437500,2,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,55
862914,1,36.5,84,20,142,114,123.333333,15.625000,2,3,...,23.575165,0.138013,95.044714,98.223145,95.384328,13.60834,1.212396,142.477514,15,55
829782,0,36.4,129,18,110,62,78.000000,28.537455,0,4,...,22.300000,0.700000,97.000000,96.000000,95.700000,14.70000,1.100000,120.000000,15,65

In [6]:
df3=pd.read_csv("drug_onehot_latest.csv",index_col=[0])
df3.head()

,Atorvastatin calcium tablet,Benazepril hydrochloride tablet,Deslanoside injection,Digoxin tablet,Dobutamine hydrochloride injection,Furosemide injection,Furosemide tablet,Hydrochlorothiazide tablet,Isoprenaline Hydrochloride injection,Isosorbide Mononitrate Sustained Release tablet,Meglumine Adenosine Cyclophosphate for injection,Milrinone injection,Nitroglycerin injection,Shenfu injection,Spironolactone tablet,Torasemide tablet,Valsartan Dispersible tablet,sulfotanshinone sodium injection
inpatient.number,,,,,,,,,,,,,,,,,,
722128,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
723327,1,0,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,0
723617,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
724385,0,0,1,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0
725509,0,0,1,1,0,1,1,0,0,0,0,1,0,1,1,1,0,0

In [7]:
q="Isoprenaline Hydrochloride injection"

In [8]:
df1.drop(['hydroxybutyrate.dehydrogenase.to.lactate.dehydrogenase','hydroxybutyrate.dehydrogenase','free.calcium','anion.gap','lactate.dehydrogenase','lactate','CCI.score','consciousness','eye.opening','verbal.response','respiratory.support.','gender','ageCat'],axis=1,inplace=True)

In [9]:
df2=df3[q]
df2 = df2.to_frame()

In [10]:
df2

                  Isoprenaline Hydrochloride injection
inpatient.number
722128                                               0
723327                                               0
723617                                               0
724385                                               0
725509                                               0
...                                                ...
870258                                               0
870646                                               0
879601                                               0
905163                                               0
905720                                               0

[2003 rows x 1 columns]

In [11]:
df=pd.concat([df1,df2],axis=1)

In [12]:
df

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS,Isoprenaline Hydrochloride injection
inpatient.number,,,,,,,,,,,,,,,,,,,,,
722128,36.900,66,18,121,56,77.666667,18.590125,2,4,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
723327,36.000,72,25,150,80,103.333333,21.644121,2,4,1,...,3.700000,-3.50000,21.900000,0.700000,91.000000,64.000000,90.000000,73.000000,15,0
723617,36.400,70,20,120,80,93.333333,33.157648,2,3,2,...,5.300000,3.90000,27.500000,0.000000,98.000000,106.000000,97.700000,104.000000,15,0
724385,36.700,129,25,122,86,98.000000,20.134780,2,3,3,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
725509,36.900,100,20,95,65,75.000000,22.031726,2,3,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870258,38.198,92,19,160,80,106.666667,17.777778,0,4,2,...,13.000000,-6.00000,19.000000,0.300000,99.000000,152.000000,98.200000,89.000000,15,0
870646,36.000,60,25,171,117,135.000000,27.281746,2,3,2,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
879601,36.500,98,19,170,65,100.000000,24.508946,2,3,2,...,8.300000,-1.80000,23.200000,1.000000,69.730000,39.000000,68.610000,102.000000,15,0
905163,36.600,108,18,140,68,92.000000,14.705882,2,3,2,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
905720,36.500,113,18,145,113,123.666667,20.811655,2,4,2,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0

In [13]:
df.head()

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS,Isoprenaline Hydrochloride injection
inpatient.number,,,,,,,,,,,,,,,,,,,,,
722128,36.9,66,18,121,56,77.666667,18.590125,2,4,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
723327,36.0,72,25,150,80,103.333333,21.644121,2,4,1,...,3.700000,-3.50000,21.900000,0.700000,91.000000,64.000000,90.000000,73.000000,15,0
723617,36.4,70,20,120,80,93.333333,33.157648,2,3,2,...,5.300000,3.90000,27.500000,0.000000,98.000000,106.000000,97.700000,104.000000,15,0
724385,36.7,129,25,122,86,98.000000,20.134780,2,3,3,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0
725509,36.9,100,20,95,65,75.000000,22.031726,2,3,1,...,5.076549,1.54824,23.575165,0.138013,95.044714,98.223145,95.384328,142.477514,15,0

In [14]:
cols_to_scale = [df.columns]

scaler = MinMaxScaler()
scaled_df= scaler.fit_transform(df)

In [15]:
df = pd.DataFrame(scaled_df,columns = df.columns)

In [16]:
df

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS,Isoprenaline Hydrochloride injection
0,0.409463,0.293103,0.125,0.480159,0.383562,0.226534,0.275119,1.0,1.0,0.000000,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
1,0.000000,0.344828,1.000,0.595238,0.547945,0.555651,0.427086,1.0,1.0,0.000000,...,0.087536,0.496900,0.453679,0.268199,0.702676,0.227979,0.701541,0.101498,1.0,0.0
2,0.181984,0.327586,0.375,0.476190,0.547945,0.427423,1.000000,1.0,0.5,0.333333,...,0.165346,0.776631,0.670658,0.000000,0.933928,0.445596,0.954083,0.359401,1.0,0.0
3,0.318471,0.836207,1.000,0.484127,0.589041,0.487263,0.351981,1.0,0.5,0.666667,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
4,0.409463,0.586207,0.375,0.376984,0.445205,0.192341,0.446373,1.0,0.5,0.000000,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,1.000000,0.517241,0.250,0.634921,0.547945,0.598393,0.234696,0.0,1.0,0.333333,...,0.539805,0.402397,0.341315,0.114943,0.966964,0.683938,0.970482,0.234609,1.0,0.0
1999,0.000000,0.241379,1.000,0.678571,0.801370,0.961703,0.707615,1.0,0.5,0.333333,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
2000,0.227480,0.568966,0.250,0.674603,0.445205,0.512908,0.569640,1.0,0.5,0.333333,...,0.311239,0.561163,0.504049,0.383142,0.000000,0.098446,0.000000,0.342762,1.0,0.0
2001,0.272975,0.655172,0.125,0.555556,0.465753,0.410327,0.081838,1.0,0.5,0.333333,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0
2002,0.227480,0.698276,0.125,0.575397,0.773973,0.816379,0.385662,1.0,1.0,0.333333,...,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0,0.0

In [17]:
#df.drop(['ageCat','gender'],axis=1,inplace=True)

# the ANN Function

In [18]:
def ANN(X_train, y_train, X_test, y_test, loss, weights):
    model = keras.Sequential([
        keras.layers.Dense(15, input_dim=65, activation='relu'),
        #keras.layers.Dense(25, input_dim=51, activation='relu'),
        #keras.layers.Dense(15, activation='relu'),
        keras.layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='rmsprop', loss=loss, metrics=['accuracy'])
    
    if weights == -1:
        model.fit(X_train, y_train, epochs=100)
    else:
        model.fit(X_train, y_train, epochs=100, class_weight = weights)
    
    print(model.evaluate(X_test, y_test))
    
    y_preds = model.predict(X_test)
    y_preds = np.round(y_preds)
    
    print("Classification Report: \n", classification_report(y_test, y_preds))
    
    return y_preds

# Principle Component Analysis

In [19]:
X = df.drop(q,axis='columns')
y = df[q]

In [20]:
X

,body.temperature,pulse,respiration,systolic.blood.pressure,diastolic.blood.pressure,map,BMI,type.of.heart.failure,NYHA.cardiac.function.classification,Killip.grade,...,sodium.ion,glucose.blood.gas,measured.residual.base,measured.bicarbonate,carboxyhemoglobin,oxygen.saturation,partial.oxygen.pressure,oxyhemoglobin,total.hemoglobin,GCS
0,0.409463,0.293103,0.125,0.480159,0.383562,0.226534,0.275119,1.0,1.0,0.000000,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0
1,0.000000,0.344828,1.000,0.595238,0.547945,0.555651,0.427086,1.0,1.0,0.000000,...,0.699395,0.087536,0.496900,0.453679,0.268199,0.702676,0.227979,0.701541,0.101498,1.0
2,0.181984,0.327586,0.375,0.476190,0.547945,0.427423,1.000000,1.0,0.5,0.333333,...,0.563075,0.165346,0.776631,0.670658,0.000000,0.933928,0.445596,0.954083,0.359401,1.0
3,0.318471,0.836207,1.000,0.484127,0.589041,0.487263,0.351981,1.0,0.5,0.666667,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0
4,0.409463,0.586207,0.375,0.376984,0.445205,0.192341,0.446373,1.0,0.5,0.000000,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998,1.000000,0.517241,0.250,0.634921,0.547945,0.598393,0.234696,0.0,1.0,0.333333,...,0.503653,0.539805,0.402397,0.341315,0.114943,0.966964,0.683938,0.970482,0.234609,1.0
1999,0.000000,0.241379,1.000,0.678571,0.801370,0.961703,0.707615,1.0,0.5,0.333333,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0
2000,0.227480,0.568966,0.250,0.674603,0.445205,0.512908,0.569640,1.0,0.5,0.333333,...,0.688909,0.311239,0.561163,0.504049,0.383142,0.000000,0.098446,0.000000,0.342762,1.0
2001,0.272975,0.655172,0.125,0.555556,0.465753,0.410327,0.081838,1.0,0.5,0.333333,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0
2002,0.227480,0.698276,0.125,0.575397,0.773973,0.816379,0.385662,1.0,1.0,0.333333,...,0.873121,0.154479,0.687731,0.518585,0.052879,0.836297,0.405301,0.878135,0.679513,1.0

In [21]:
y.to_frame()

      Isoprenaline Hydrochloride injection
0                                      0.0
1                                      0.0
2                                      0.0
3                                      0.0
4                                      0.0
...                                    ...
1998                                   0.0
1999                                   0.0
2000                                   0.0
2001                                   0.0
2002                                   0.0

[2003 rows x 1 columns]

In [22]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)
PCA_df = pd.DataFrame(data = X_pca)
PCA_df.to_csv("FeaturesPCA_dropped.csv")
PCA_df = pd.concat([PCA_df, df[q]], axis = 1)
PCA_df.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,Isoprenaline Hydrochloride injection
0,-0.572855,0.775703,-0.555175,-0.668609,0.206971,0.311069,0.004777,-0.218921,0.021354,0.522483,...,0.117052,0.313998,0.083378,0.270367,0.613181,-0.032338,-0.291381,-0.346303,-0.057003,0.0
1,0.378881,-0.054257,-0.140639,-0.745776,0.054000,-0.078432,0.065719,-0.312667,-0.300151,0.531537,...,0.130041,-0.281455,-0.216349,0.080771,0.129352,0.079545,-0.117099,0.032437,0.089642,0.0
2,0.378855,-0.298639,-0.214987,-0.136841,-0.174487,0.944021,0.676052,0.005444,0.292429,-0.035979,...,0.162750,0.056158,0.233953,0.037804,-0.182907,0.073337,0.190404,0.210340,-0.395110,0.0
3,-0.385298,0.650624,-0.147322,-0.262479,0.156089,0.317733,-0.001556,-0.057074,0.389654,0.725043,...,-0.025797,0.037880,0.050543,0.093189,0.009083,0.240156,-0.030918,0.150497,-0.147013,0.0
4,-0.721262,-0.141627,0.296722,0.191071,-0.157643,-0.106280,0.209430,0.399258,-0.148421,0.039294,...,-0.083293,0.046128,-0.067033,0.065144,0.102891,0.149844,0.059303,-0.015103,-0.049884,0.0

# OverSampling

In [23]:
count_class_0, count_class_1 = PCA_df[q].value_counts()[0], PCA_df[q].value_counts()[1]
# Divide by class
df_class_0 = PCA_df[PCA_df[q] == 0]
df_class_1 = PCA_df[PCA_df[q] == 1]

In [24]:
PCA_df[q].value_counts(ascending =True)

1.0      30
0.0    1973
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [25]:
PCA_df[q].value_counts()

0.0    1973
1.0      30
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [26]:
# Oversample 1-class and concat the DataFrames of both classes( if count of 0 greater than count of 1)
# Oversample 0-class and concat the DataFrames of both classes( if count of 0 lesser than count of 1)
if count_class_0>count_class_1:
    df_class_1_over = df_class_1.sample(count_class_0, replace=True)
    df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

    print('Random over-sampling:')
    print(df_test_over[q].value_counts())
else:
    df_class_0_over = df_class_0.sample(count_class_1,replace=True)
    df_test_over = pd.concat([df_class_0_over, df_class_1], axis=0)

    print('Random over-sampling:')
    print(df_test_over[q].value_counts())

Random over-sampling:
0.0    1973
1.0    1973
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [27]:
X = df_test_over.drop(q,axis='columns')
y = df_test_over[q]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)

In [28]:
# Number of classes in training Data
y_train.value_counts()

0.0    1578
1.0    1578
Name: Isoprenaline Hydrochloride injection, dtype: int64

In [29]:
loss = keras.losses.BinaryCrossentropy()
weights = -1
y_preds = ANN(X_train, y_train, X_test, y_test, 'binary_crossentropy', -1)

Epoch 1/100
99/99 [==============================] - 0s 889us/step - loss: 0.5987 - accuracy: 0.7490
Epoch 2/100
99/99 [==============================] - 0s 845us/step - loss: 0.4835 - accuracy: 0.8580
Epoch 3/100
99/99 [==============================] - 0s 817us/step - loss: 0.3911 - accuracy: 0.8888
Epoch 4/100
99/99 [==============================] - 0s 837us/step - loss: 0.3173 - accuracy: 0.9287
Epoch 5/100
99/99 [==============================] - 0s 852us/step - loss: 0.2599 - accuracy: 0.9499
Epoch 6/100
99/99 [==============================] - 0s 888us/step - loss: 0.2163 - accuracy: 0.9588
Epoch 7/100
99/99 [==============================] - 0s 888us/step - loss: 0.1832 - accuracy: 0.9617
Epoch 8/100
99/99 [==============================] - 0s 973us/step - loss: 0.1574 - accuracy: 0.9667
Epoch 9/100
99/99 [==============================] - 0s 858us/step - loss: 0.1368 - accuracy: 0.9696
Epoch 10/100
99/99 [==============================] - 0s 841us/step - loss: 0.1200 - accuracy: 0.9715
Epoch 11/100
99/99 [==============================] - 0s 868us/step - loss: 0.1061 - accuracy: 0.9759
Epoch 12/100
99/99 [==============================] - 0s 870us/step - loss: 0.0943 - accuracy: 0.9788
Epoch 13/100
99/99 [==============================] - 0s 831us/step - loss: 0.0840 - accuracy: 0.9810
Epoch 14/100
99/99 [==============================] - 0s 839us/step - loss: 0.0751 - accuracy: 0.9835
Epoch 15/100
99/99 [==============================] - 0s 848us/step - loss: 0.0669 - accuracy: 0.9857
Epoch 16/100
99/99 [==============================] - 0s 819us/step - loss: 0.0598 - accuracy: 0.9873
Epoch 17/100
99/99 [==============================] - 0s 795us/step - loss: 0.0536 - accuracy: 0.9895
Epoch 18/100
99/99 [==============================] - 0s 847us/step - loss: 0.0483 - accuracy: 0.9902
Epoch 19/100
99/99 [==============================] - 0s 844us/step - loss: 0.0435 - accuracy: 0.9908
Epoch 20/100
99/99 [==============================] - 0s 840us/step - loss: 0.0393 - accuracy: 0.9921
Epoch 21/100
99/99 [==============================] - 0s 824us/step - loss: 0.0356 - accuracy: 0.9924
Epoch 22/100
99/99 [==============================] - 0s 818us/step - loss: 0.0324 - accuracy: 0.9927
Epoch 23/100
99/99 [==============================] - 0s 788us/step - loss: 0.0293 - accuracy: 0.9937
Epoch 24/100
99/99 [==============================] - 0s 856us/step - loss: 0.0264 - accuracy: 0.9949
Epoch 25/100
99/99 [==============================] - 0s 803us/step - loss: 0.0242 - accuracy: 0.9956
Epoch 26/100
99/99 [==============================] - 0s 826us/step - loss: 0.0222 - accuracy: 0.9965
Epoch 27/100
99/99 [==============================] - 0s 810us/step - loss: 0.0202 - accuracy: 0.9971
Epoch 28/100
99/99 [==============================] - 0s 827us/step - loss: 0.0183 - accuracy: 0.9971
Epoch 29/100
99/99 [==============================] - 0s 826us/step - loss: 0.0167 - accuracy: 0.9975
Epoch 30/100
99/99 [==============================] - 0s 847us/step - loss: 0.0152 - accuracy: 0.9978
Epoch 31/100
99/99 [==============================] - 0s 822us/step - loss: 0.0138 - accuracy: 0.9978
Epoch 32/100
99/99 [==============================] - 0s 829us/step - loss: 0.0127 - accuracy: 0.9978
Epoch 33/100
99/99 [==============================] - 0s 779us/step - loss: 0.0116 - accuracy: 0.9981
Epoch 34/100
99/99 [==============================] - 0s 845us/step - loss: 0.0106 - accuracy: 0.9984
Epoch 35/100
99/99 [==============================] - 0s 811us/step - loss: 0.0097 - accuracy: 0.9984
Epoch 36/100
99/99 [==============================] - 0s 822us/step - loss: 0.0088 - accuracy: 0.9984
Epoch 37/100
99/99 [==============================] - 0s 816us/step - loss: 0.0081 - accuracy: 0.9984
Epoch 38/100
99/99 [==============================] - 0s 811us/step - loss: 0.0076 - accuracy: 0.9984
Epoch 39/100
99/99 [==============================] - 0s 856us/step - loss: 0.0068 - accuracy: 0.9984
Epoch 40/100
99/99 [==============================] - 0s 798us/step - loss: 0.0065 - accuracy: 0.9984
Epoch 41/100
99/99 [==============================] - 0s 812us/step - loss: 0.0057 - accuracy: 0.9987
Epoch 42/100
99/99 [==============================] - 0s 838us/step - loss: 0.0054 - accuracy: 0.9990
Epoch 43/100
99/99 [==============================] - 0s 759us/step - loss: 0.0048 - accuracy: 0.9990
Epoch 44/100
99/99 [==============================] - 0s 796us/step - loss: 0.0043 - accuracy: 0.9990
Epoch 45/100
99/99 [==============================] - 0s 839us/step - loss: 0.0038 - accuracy: 0.9990
Epoch 46/100
99/99 [==============================] - 0s 801us/step - loss: 0.0037 - accuracy: 0.9990
Epoch 47/100
99/99 [==============================] - 0s 815us/step - loss: 0.0032 - accuracy: 0.9994
Epoch 48/100
99/99 [==============================] - 0s 828us/step - loss: 0.0030 - accuracy: 0.9994
Epoch 49/100
99/99 [==============================] - 0s 787us/step - loss: 0.0026 - accuracy: 0.9994
Epoch 50/100
99/99 [==============================] - 0s 828us/step - loss: 0.0024 - accuracy: 0.9994
Epoch 51/100
99/99 [==============================] - 0s 841us/step - loss: 0.0021 - accuracy: 0.9994
Epoch 52/100
99/99 [==============================] - 0s 820us/step - loss: 0.0019 - accuracy: 0.9997
Epoch 53/100
99/99 [==============================] - 0s 793us/step - loss: 0.0017 - accuracy: 0.9997
Epoch 54/100
99/99 [==============================] - 0s 811us/step - loss: 0.0015 - accuracy: 0.9997
Epoch 55/100
99/99 [==============================] - 0s 804us/step - loss: 0.0013 - accuracy: 0.9997
Epoch 56/100
99/99 [==============================] - 0s 810us/step - loss: 0.0012 - accuracy: 0.9997
Epoch 57/100
99/99 [==============================] - 0s 800us/step - loss: 0.0011 - accuracy: 0.9997
Epoch 58/100
99/99 [==============================] - 0s 821us/step - loss: 9.5263e-04 - accuracy: 0.9997
Epoch 59/100
99/99 [==============================] - 0s 830us/step - loss: 9.2951e-04 - accuracy: 0.9997
Epoch 60/100
99/99 [==============================] - 0s 842us/step - loss: 8.0214e-04 - accuracy: 0.9997
Epoch 61/100
99/99 [==============================] - 0s 788us/step - loss: 6.9550e-04 - accuracy: 0.9997
Epoch 62/100
99/99 [==============================] - 0s 822us/step - loss: 6.1485e-04 - accuracy: 0.9997
Epoch 63/100
99/99 [==============================] - 0s 830us/step - loss: 5.1353e-04 - accuracy: 1.0000
Epoch 64/100
99/99 [==============================] - 0s 852us/step - loss: 4.8926e-04 - accuracy: 0.9997
Epoch 65/100
99/99 [==============================] - 0s 794us/step - loss: 3.9384e-04 - accuracy: 1.0000
Epoch 66/100
99/99 [==============================] - 0s 838us/step - loss: 3.9643e-04 - accuracy: 1.0000
Epoch 67/100
99/99 [==============================] - 0s 849us/step - loss: 3.0448e-04 - accuracy: 1.0000
Epoch 68/100
99/99 [==============================] - 0s 789us/step - loss: 2.7435e-04 - accuracy: 1.0000
Epoch 69/100
99/99 [==============================] - 0s 891us/step - loss: 2.1000e-04 - accuracy: 1.0000
Epoch 70/100
99/99 [==============================] - 0s 837us/step - loss: 2.2546e-04 - accuracy: 1.0000
Epoch 71/100
99/99 [==============================] - 0s 953us/step - loss: 1.8215e-04 - accuracy: 1.0000
Epoch 72/100
99/99 [==============================] - 0s 854us/step - loss: 1.6796e-04 - accuracy: 1.0000
Epoch 73/100
99/99 [==============================] - 0s 827us/step - loss: 1.3831e-04 - accuracy: 1.0000
Epoch 74/100
99/99 [==============================] - 0s 787us/step - loss: 1.2043e-04 - accuracy: 1.0000
Epoch 75/100
99/99 [==============================] - 0s 812us/step - loss: 9.1911e-05 - accuracy: 1.0000
Epoch 76/100
99/99 [==============================] - 0s 805us/step - loss: 8.9055e-05 - accuracy: 1.0000
Epoch 77/100
99/99 [==============================] - 0s 830us/step - loss: 7.3679e-05 - accuracy: 1.0000
Epoch 78/100
99/99 [==============================] - 0s 828us/step - loss: 6.5451e-05 - accuracy: 1.0000
Epoch 79/100
99/99 [==============================] - 0s 798us/step - loss: 4.9694e-05 - accuracy: 1.0000
Epoch 80/100
99/99 [==============================] - 0s 815us/step - loss: 4.5254e-05 - accuracy: 1.0000
Epoch 81/100
99/99 [==============================] - 0s 816us/step - loss: 4.5341e-05 - accuracy: 1.0000
Epoch 82/100
99/99 [==============================] - 0s 779us/step - loss: 3.3904e-05 - accuracy: 1.0000
Epoch 83/100
99/99 [==============================] - 0s 808us/step - loss: 2.8998e-05 - accuracy: 1.0000
Epoch 84/100
99/99 [==============================] - 0s 814us/step - loss: 2.2675e-05 - accuracy: 1.0000
Epoch 85/100
99/99 [==============================] - 0s 850us/step - loss: 2.3449e-05 - accuracy: 1.0000
Epoch 86/100
99/99 [==============================] - 0s 843us/step - loss: 1.7189e-05 - accuracy: 1.0000
Epoch 87/100
99/99 [==============================] - 0s 820us/step - loss: 1.5209e-05 - accuracy: 1.0000
Epoch 88/100
99/99 [==============================] - 0s 801us/step - loss: 1.2901e-05 - accuracy: 1.0000
Epoch 89/100
99/99 [==============================] - 0s 838us/step - loss: 1.0557e-05 - accuracy: 1.0000
Epoch 90/100
99/99 [==============================] - 0s 842us/step - loss: 9.0843e-06 - accuracy: 1.0000
Epoch 91/100
99/99 [==============================] - 0s 814us/step - loss: 7.1916e-06 - accuracy: 1.0000
Epoch 92/100
99/99 [==============================] - 0s 842us/step - loss: 6.2216e-06 - accuracy: 1.0000
Epoch 93/100
99/99 [==============================] - 0s 838us/step - loss: 5.5353e-06 - accuracy: 1.0000
Epoch 94/100
99/99 [==============================] - 0s 805us/step - loss: 4.9277e-06 - accuracy: 1.0000
Epoch 95/100
99/99 [==============================] - 0s 864us/step - loss: 3.9300e-06 - accuracy: 1.0000
Epoch 96/100
99/99 [==============================] - 0s 841us/step - loss: 3.3490e-06 - accuracy: 1.0000
Epoch 97/100
99/99 [==============================] - 0s 811us/step - loss: 2.9521e-06 - accuracy: 1.0000
Epoch 98/100
99/99 [==============================] - 0s 780us/step - loss: 2.4516e-06 - accuracy: 1.0000
Epoch 99/100
99/99 [==============================] - 0s 834us/step - loss: 2.1138e-06 - accuracy: 1.0000
Epoch 100/100
99/99 [==============================] - 0s 865us/step - loss: 1.7392e-06 - accuracy: 1.0000
25/25 [==============================] - 0s 788us/step - loss: 0.0305 - accuracy: 0.9924
[0.030507713556289673, 0.9924050569534302]
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      0.98      0.99       395
         1.0       0.99      1.00      0.99       395

    accuracy                           0.99       790
   macro avg       0.99      0.99      0.99       790
weighted avg       0.99      0.99      0.99       790

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15, stratify=y)
mlp = MLPClassifier(hidden_layer_sizes=(8,  1), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(8, 1), max_iter=1000)

In [31]:
predictions = mlp.predict(X_test)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[384  11]
 [341  54]]
              precision    recall  f1-score   support

         0.0       0.53      0.97      0.69       395
         1.0       0.83      0.14      0.23       395

    accuracy                           0.55       790
   macro avg       0.68      0.55      0.46       790
weighted avg       0.68      0.55      0.46       790